"""add search_field tsvector to products

Revision ID: 527f7bacbbe5
Revises: fd59a515fd36
Create Date: 2025-04-21 14:06:57.295674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '527f7bacbbe5'
down_revision: Union[str, None] = 'fd59a515fd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sql = (
        "ALTER TABLE products ADD COLUMN search_field tsvector "
        "GENERATED ALWAYS AS ("
        "setweight(to_tsvector('french', name), 'A')"
        ") STORED;"
    )
    op.execute(sql)
    op.execute("CREATE INDEX idx_search_field ON products USING GIN (search_field)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'search_field')
    op.drop_index('idx_search_field', table_name='products')
    # ### end Alembic commands ###
