"""add search_field to recipes

Revision ID: b87793ef2b3d
Revises: 1935e0c5f7b8
Create Date: 2025-04-21 14:57:47.462340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87793ef2b3d'
down_revision: Union[str, None] = '1935e0c5f7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sql = (
        "ALTER TABLE recipes ADD COLUMN search_field tsvector "
        "GENERATED ALWAYS AS ("
        "setweight(to_tsvector('french', title), 'A') ||"
        "setweight(to_tsvector('french', description), 'B') ||"
        "setweight(to_tsvector('french', instructions), 'C')"
        ") STORED;"
    )
    op.execute(sql)
    op.execute("CREATE INDEX idx_recipes_search_field ON recipes USING GIN (search_field)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'search_field')
    op.drop_index('idx_recipes_search_field', table_name='recipes')
    # ### end Alembic commands ###
