"""add search_field to products

Revision ID: 1935e0c5f7b8
Revises: 2cfa9b6647d9
Create Date: 2025-04-21 14:56:30.915359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1935e0c5f7b8'
down_revision: Union[str, None] = '2cfa9b6647d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sql = (
        "ALTER TABLE products ADD COLUMN search_field tsvector "
        "GENERATED ALWAYS AS ("
        "setweight(to_tsvector('french', name), 'A')"
        ") STORED;"
    )
    op.execute(sql)
    op.execute("CREATE INDEX idx_products_search_field ON products USING GIN (search_field)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'search_field')
    op.drop_index('idx_products_search_field', table_name='products')
    # ### end Alembic commands ###
