services:
  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api_db
    volumes:
      - lifprojet_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U pgweb -h 127.0.0.1
      interval: 5s
    restart: unless-stopped
    ports:
      - "5432:5432"

  # pgweb (GUI for PGSQL)
  pgweb:
    image: sosedoff/pgweb:latest
    environment:
      - PGWEB_DATABASE_URL=postgres://api:api@db:5432/api_db?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-vz", "127.0.0.1", "8081" ]
      interval: 5s
    restart: unless-stopped

volumes:
  lifprojet_data: