"""Initial migration

Revision ID: 29d198c1426a
Revises: 
Create Date: 2025-03-08 17:15:54.095204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d198c1426a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_industrials',
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('carbohydrates', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('fiber', sa.Integer(), nullable=False),
    sa.Column('proteins', sa.Integer(), nullable=False),
    sa.Column('salt', sa.Integer(), nullable=False),
    sa.Column('saturated_fat', sa.Integer(), nullable=False),
    sa.Column('fruits_vegetables_nuts_estimate', sa.Integer(), nullable=False),
    sa.Column('sugars', sa.Integer(), nullable=False),
    sa.Column('sodium', sa.Integer(), nullable=False),
    sa.Column('nutriscore', sa.String(length=100), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('date_modified', sa.Date(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('information', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products_industrials')
    # ### end Alembic commands ###
