"""add product model and fts

Revision ID: 499a72b67202
Revises: e3c974a49251
Create Date: 2025-04-19 13:16:02.824578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499a72b67202'
down_revision = 'e3c974a49251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('drink', 'cheese', 'fat', 'other', name='product_category'), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('sugars', sa.Float(), nullable=False),
    sa.Column('saturated_fat', sa.Float(), nullable=False),
    sa.Column('salt', sa.Float(), nullable=False),
    sa.Column('fruits_veg', sa.Float(), nullable=False),
    sa.Column('fibers', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    # Create FTS Index for name field manually because not supported by Flask Migrate
    op.execute(
        "CREATE INDEX product_name_fts_idx ON products USING GIN (to_tsvector('french', name))"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
