"""add nutriscore field to recipe

Revision ID: 93d3af2f0664
Revises: c44c39312115
Create Date: 2025-04-20 00:28:06.822604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d3af2f0664'
down_revision = 'c44c39312115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutriscore', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('nutriscore')

    # ### end Alembic commands ###
