"""switch information field in product to text

Revision ID: c36e32ee497c
Revises: b3629b44e7db
Create Date: 2025-03-10 18:58:47.396384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36e32ee497c'
down_revision = 'b3629b44e7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_industrials', schema=None) as batch_op:
        batch_op.alter_column('information',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_industrials', schema=None) as batch_op:
        batch_op.alter_column('information',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
