"""Product barcode to string

Revision ID: c67fbc63a976
Revises: 29d198c1426a
Create Date: 2025-03-08 17:27:19.096461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67fbc63a976'
down_revision = '29d198c1426a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_industrials', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_industrials', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
