"""add bio and preferences field at users

Revision ID: e3c974a49251
Revises: c5d9762d93f5
Create Date: 2025-04-19 12:21:00.134948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3c974a49251'
down_revision = 'c5d9762d93f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
